### ISSUE TITLE
Detail view of objects are not returning ID! 

### ISSUE THREAD

**Issue by navidkhn1** [bigdroptech/square1-core#147]
Tested with user object. Other objects need to be checked.

**Comment by elflamo** [comment]
On it

**Comment by elflamo** [comment]
ListCreateProductView not working

**Comment by elflamo** [comment]
To do: Create Post must contain -> get or create author

**Comment by elflamo** [comment]
Update: Is there any need for returning configuration id? since it is going to be always 1.

**Comment by elflamo** [comment]
Done.

**Comment by navidkhn1** [comment]
@elflamo , my my, all these comments! Yes, we need ID with configuration as well. What happens if a user happens to change settings? :)

**Comment by elflamo** [comment]
@navidkhn1 Updating the settings works. It changes the original settings. Push the code again in issue147 branch.

**Comment by elflamo** [comment]
@navidkhn1 Done, kindly Review PR https://github.com/bigdroptech/square1-core/pull/154
